//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetworkService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkService.Resources.NetworkService", typeof(NetworkService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string BlackColor {
            get {
                return ResourceManager.GetString("BlackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable sensor.
        /// </summary>
        internal static string CableSensorString {
            get {
                return ResourceManager.GetString("CableSensorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string ColorBlue {
            get {
                return ResourceManager.GetString("ColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2B55FF.
        /// </summary>
        internal static string ColorLightBlue {
            get {
                return ResourceManager.GetString("ColorLightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string ColorWhite {
            get {
                return ResourceManager.GetString("ColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital manometar.
        /// </summary>
        internal static string DigitalManometarString {
            get {
                return ResourceManager.GetString("DigitalManometarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see five last mesurements and\n theirs values you need to select \nentity from Combobox\n
        ///                    --------------------------------------\n
        ///                \nSHORTCUTS\n
        ///                \nHome Ctrl+1\n
        ///                Table Ctrl+2\n
        ///                Grid Ctrl+3\n
        ///                Graphic Ctrl+4\n
        ///                Turn off help Ctrl+H\n
        ///                Exit Esc.
        /// </summary>
        internal static string GraphHelp {
            get {
                return ResourceManager.GetString("GraphHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string GrayColor {
            get {
                return ResourceManager.GetString("GrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select entity from tree view and\n put on the network.\n--------------------------------------\n
        ///                           You can change  position of \nentity on the grid.\nDrag and drop from canvas \nto another canvas.\n
        ///                --------------------------------------\n
        ///                To connect the entities \nin grid you have to\nhold the right click\nand drag to the desired one.\n
        ///                --------------------------------------\n
        ///                To delete entities from grid\npress b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GridHelp {
            get {
                return ResourceManager.GetString("GridHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To go to the table page press\n the TABLE button\n
        ///                 -------------------------\n
        ///                To go to the grid page press\n the GRID button\n
        ///                 -------------------------\n
        ///                To go to the graphic page press\n the GRAPHIC button\n
        ///                 -------------------------\n
        ///                To exit from app press\n EXIT button\n
        ///                    \nSHORTCUTS\n
        ///                \nHome Ctrl+1\n
        ///                Table Ctrl+2\n
        ///                Grid Ctrl+3\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeHelp {
            get {
                return ResourceManager.GetString("HomeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSteelBlue.
        /// </summary>
        internal static string LightBlueColor {
            get {
                return ResourceManager.GetString("LightBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string RedColor {
            get {
                return ResourceManager.GetString("RedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete entity you need to\nselect it from table\nand press DELETE button\n
        ///               ------------------------------------\n
        ///                            To serach entities you need to\nchose do you want \nto seach by type or name\nand type text in search input\nand press button SEARCH\n
        ///               -------------------------------------\n
        ///                             To restore table in previus state\npress button RESET SEARCH\n
        ///               --------------------------------------\n
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableHelp {
            get {
                return ResourceManager.GetString("TableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input id here.
        /// </summary>
        internal static string TableViewModel_Id {
            get {
                return ResourceManager.GetString("TableViewModel_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name here.
        /// </summary>
        internal static string TableViewModel_Name {
            get {
                return ResourceManager.GetString("TableViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input search here.
        /// </summary>
        internal static string TableViewModel_Search {
            get {
                return ResourceManager.GetString("TableViewModel_Search", resourceCulture);
            }
        }
    }
}
